services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  adservice:
    build:
      context: .
      dockerfile: ad/Dockerfile
    container_name: adservice
    ports:
      - "8000:8000"
    env_file:
      - ./ad/.env
    depends_on:
      - mongodb

  trackerservice:
    build:
      context: .
      dockerfile: tracker/Dockerfile
    container_name: trackerservice
    ports:
      - "9000:9000"
    env_file:
      - ./tracker/.env
    depends_on:
      - mongodb
      - adservice

volumes:
  dragonflydata:
  mongodb_data:
