// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: protos/ad.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_protos_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ad) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetAdByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdByIdRequest) Reset() {
	*x = GetAdByIdRequest{}
	mi := &file_protos_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdByIdRequest) ProtoMessage() {}

func (x *GetAdByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAdByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{1}
}

func (x *GetAdByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdByIdResponse) Reset() {
	*x = GetAdByIdResponse{}
	mi := &file_protos_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdByIdResponse) ProtoMessage() {}

func (x *GetAdByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAdByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdByIdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_protos_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_protos_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_protos_ad_proto protoreflect.FileDescriptor

const file_protos_ad_proto_rawDesc = "" +
	"\n" +
	"\x0fprotos/ad.proto\x12\x02ad\"^\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\"\n" +
	"\x10GetAdByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11GetAdByIdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"[\n" +
	"\x0fCreateAdRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\"\n" +
	"\x10CreateAdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2|\n" +
	"\tAdService\x128\n" +
	"\tGetAdById\x12\x14.ad.GetAdByIdRequest\x1a\x15.ad.GetAdByIdResponse\x125\n" +
	"\bCreateAd\x12\x13.ad.CreateAdRequest\x1a\x14.ad.CreateAdResponseB\x10Z\x0ead/proto;protob\x06proto3"

var (
	file_protos_ad_proto_rawDescOnce sync.Once
	file_protos_ad_proto_rawDescData []byte
)

func file_protos_ad_proto_rawDescGZIP() []byte {
	file_protos_ad_proto_rawDescOnce.Do(func() {
		file_protos_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ad_proto_rawDesc), len(file_protos_ad_proto_rawDesc)))
	})
	return file_protos_ad_proto_rawDescData
}

var file_protos_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_ad_proto_goTypes = []any{
	(*Ad)(nil),                // 0: ad.Ad
	(*GetAdByIdRequest)(nil),  // 1: ad.GetAdByIdRequest
	(*GetAdByIdResponse)(nil), // 2: ad.GetAdByIdResponse
	(*CreateAdRequest)(nil),   // 3: ad.CreateAdRequest
	(*CreateAdResponse)(nil),  // 4: ad.CreateAdResponse
}
var file_protos_ad_proto_depIdxs = []int32{
	0, // 0: ad.GetAdByIdResponse.ad:type_name -> ad.Ad
	1, // 1: ad.AdService.GetAdById:input_type -> ad.GetAdByIdRequest
	3, // 2: ad.AdService.CreateAd:input_type -> ad.CreateAdRequest
	2, // 3: ad.AdService.GetAdById:output_type -> ad.GetAdByIdResponse
	4, // 4: ad.AdService.CreateAd:output_type -> ad.CreateAdResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_ad_proto_init() }
func file_protos_ad_proto_init() {
	if File_protos_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ad_proto_rawDesc), len(file_protos_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ad_proto_goTypes,
		DependencyIndexes: file_protos_ad_proto_depIdxs,
		MessageInfos:      file_protos_ad_proto_msgTypes,
	}.Build()
	File_protos_ad_proto = out.File
	file_protos_ad_proto_goTypes = nil
	file_protos_ad_proto_depIdxs = nil
}
