// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: tracker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tracker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdId          string                 `protobuf:"bytes,2,opt,name=adId,proto3" json:"adId,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracker) Reset() {
	*x = Tracker{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracker) ProtoMessage() {}

func (x *Tracker) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracker.ProtoReflect.Descriptor instead.
func (*Tracker) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *Tracker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tracker) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *Tracker) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateTrackerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=adId,proto3" json:"adId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackerRequest) Reset() {
	*x = CreateTrackerRequest{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackerRequest) ProtoMessage() {}

func (x *CreateTrackerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackerRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackerRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrackerRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type CreateTrackerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracker       *Tracker               `protobuf:"bytes,1,opt,name=tracker,proto3" json:"tracker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackerResponse) Reset() {
	*x = CreateTrackerResponse{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackerResponse) ProtoMessage() {}

func (x *CreateTrackerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackerResponse.ProtoReflect.Descriptor instead.
func (*CreateTrackerResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTrackerResponse) GetTracker() *Tracker {
	if x != nil {
		return x.Tracker
	}
	return nil
}

type UpdateCountTrackerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=adId,proto3" json:"adId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCountTrackerRequest) Reset() {
	*x = UpdateCountTrackerRequest{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCountTrackerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCountTrackerRequest) ProtoMessage() {}

func (x *UpdateCountTrackerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCountTrackerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCountTrackerRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCountTrackerRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type UpdateCountTrackerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracker       *Tracker               `protobuf:"bytes,1,opt,name=tracker,proto3" json:"tracker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCountTrackerResponse) Reset() {
	*x = UpdateCountTrackerResponse{}
	mi := &file_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCountTrackerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCountTrackerResponse) ProtoMessage() {}

func (x *UpdateCountTrackerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCountTrackerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCountTrackerResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCountTrackerResponse) GetTracker() *Tracker {
	if x != nil {
		return x.Tracker
	}
	return nil
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\atracker\"C\n" +
	"\aTracker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04adId\x18\x02 \x01(\tR\x04adId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"*\n" +
	"\x14CreateTrackerRequest\x12\x12\n" +
	"\x04adId\x18\x01 \x01(\tR\x04adId\"C\n" +
	"\x15CreateTrackerResponse\x12*\n" +
	"\atracker\x18\x01 \x01(\v2\x10.tracker.TrackerR\atracker\"/\n" +
	"\x19UpdateCountTrackerRequest\x12\x12\n" +
	"\x04adId\x18\x01 \x01(\tR\x04adId\"H\n" +
	"\x1aUpdateCountTrackerResponse\x12*\n" +
	"\atracker\x18\x01 \x01(\v2\x10.tracker.TrackerR\atracker2\xbf\x01\n" +
	"\x0eTrackerService\x12N\n" +
	"\rCreateTracker\x12\x1d.tracker.CreateTrackerRequest\x1a\x1e.tracker.CreateTrackerResponse\x12]\n" +
	"\x12UpdateCountTracker\x12\".tracker.UpdateCountTrackerRequest\x1a#.tracker.UpdateCountTrackerResponseB\x15Z\x13tracker/proto;protob\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tracker_proto_goTypes = []any{
	(*Tracker)(nil),                    // 0: tracker.Tracker
	(*CreateTrackerRequest)(nil),       // 1: tracker.CreateTrackerRequest
	(*CreateTrackerResponse)(nil),      // 2: tracker.CreateTrackerResponse
	(*UpdateCountTrackerRequest)(nil),  // 3: tracker.UpdateCountTrackerRequest
	(*UpdateCountTrackerResponse)(nil), // 4: tracker.UpdateCountTrackerResponse
}
var file_tracker_proto_depIdxs = []int32{
	0, // 0: tracker.CreateTrackerResponse.tracker:type_name -> tracker.Tracker
	0, // 1: tracker.UpdateCountTrackerResponse.tracker:type_name -> tracker.Tracker
	1, // 2: tracker.TrackerService.CreateTracker:input_type -> tracker.CreateTrackerRequest
	3, // 3: tracker.TrackerService.UpdateCountTracker:input_type -> tracker.UpdateCountTrackerRequest
	2, // 4: tracker.TrackerService.CreateTracker:output_type -> tracker.CreateTrackerResponse
	4, // 5: tracker.TrackerService.UpdateCountTracker:output_type -> tracker.UpdateCountTrackerResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
